# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20170913_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
    ]
